language: sh
services:
  -docker
script:
  - docker build -t fs-capstone .
  - docker run fs-capstone flake8 src test
  - docker run fs-capstone pytest test
deploy:   
    provider: script
    script:
      curl https://cli-assets.heroku.com/install.sh | sh;
      echo $HEROKU_API_KEY | docker login --username=$HEROKU_LOGIN --password-stdin registry.heroku.com;
      docker tag fs-capstone registry.heroku.com/$HEROKU_APP/web;
      docker push registry.heroku.com/$HEROKU_APP/web;
      heroku container:release web --app $HEROKU_APP
    on:
      branch: master
