version: "3.8"
services:
  webapp:
    build:
      context: .
    ports:
      - 80:5000
    environment:
      DATABASE_URL: postgres://postgres:pgpass@postgres:5432/postgres
      FLASK_ENV: development
    command: /bin/sh -c "flask db upgrade && flask run -h 0.0.0.0"
    volumes:
      - .:/app:cached
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_PASSWORD: pgpass
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: