version: "3.8"
services:
  webapp:
    build:
      context: .
    ports:
      - 80:5000
    environment:
      AUTH0_DOMAIN: ufs-casting-agency.us.auth0.com
      API_AUDIENCE: https://ufs-casting-agency.herokuapp.com/api
      ALGORITHMS: RS256
      DATABASE_URL: postgres://postgres:pgpass@postgres:5432/postgres
      PORT: 5000
      FLASK_ENV: development
    command: /bin/sh -c "flask db upgrade && flask run -h 0.0.0.0"
    volumes:
      - .:/app
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_PASSWORD: pgpass
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: